version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tabela-backend
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=pemeliharaan_aset_bpom
      - DB_PASSWORD=abWTBenzFpLGPR3L
      - DB_NAME=pemeliharaan_aset_bpom
      - KEYCLOAK_SERVER_URL=https://auth.bbpompky.id
      - KEYCLOAK_REALM=master
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=ontageniT1!
      - NODE_ENV=production
      - PORT=5002
      # Tambahkan environment variable untuk path data
      - DATA_PATH=/data
      - LOGS_PATH=/data/logs
      - UPLOADS_PATH=/data/uploads
    volumes:
      # Mount folder data untuk backend
      - ./data/backend:/data
      # Untuk development - kode sumber
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://data-tabela.bbpompky.id/api
        NEXT_PUBLIC_KEYCLOAK_ISSUER: https://auth.bbpompky.id/realms/master
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: pemeliharaan
    container_name: tabela-frontend
    restart: unless-stopped
    ports:
      - "3003:3003"  # ⭐ Host:3003 → Container:3003
    environment:
      - NODE_ENV=production
      # ⭐ Gunakan domain tunnel untuk NextAuth
      - NEXT_PUBLIC_API_URL=https://data-tabela.bbpompky.id/api
      - KEYCLOAK_ISSUER=https://auth.bbpompky.id/realms/master
      - KEYCLOAK_CLIENT_ID=pemeliharaan
      - KEYCLOAK_CLIENT_SECRET=aYjH7KsPnoivQaSCQSl6yScQnyGXCPEk
      - NEXTAUTH_URL=https://tabela-raya.bbpompky.id
      - NEXTAUTH_SECRET=dnpp//pRJuxPWuZsWUBX4YB0BAxORPt7dRR/MX91KEA=
      - KEYCLOAK_ADMIN_USERNAME=admin
      - KEYCLOAK_ADMIN_PASSWORD=ontageniT1!
      # Tambahkan environment variable untuk path data frontend
      - DATA_PATH=/data
      - CACHE_PATH=/data/.next/cache
      - PUBLIC_UPLOADS_PATH=/data/public/uploads
    volumes:
      # Mount folder data untuk frontend
      - ./data/frontend:/data
      # Untuk development - kode sumber
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    depends_on:
      - backend